# Generated by Django 4.0.6 on 2022-07-21 13:43

from django.db import migrations
from apps.blog.models import BlockCategory


def add_blog_categories(apps, schema_editor):
    categories = [
        'Новости',
        'Обзоры',
        'Акции',
        'Партнерам',
        'Специальные предложения'
    ]
    for category in categories:
        BlockCategory.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_tags'),
    ]

    operations = [
        migrations.RunPython(add_blog_categories)
    ]
